### ISSUE TITLE
AttributeError: module 'tempfile' has no attribute 'mkstemp'

### ISSUE THREAD

**Issue by BrightXiaoHan** [OpenNMT/Tokenizer#259]
This is my code
```
import pyonmttok

tokenizer = pyonmttok.Tokenizer("aggressive", segment_alphabet_change=True, segment_alphabet=["Han"])
learner = pyonmttok.SentencePieceLearner(vocab_size=32000, character_coverage=0.98)
```
It raised AttributeError
```
Traceback (most recent call last):
  File "tokenize.py", line 4, in <module>
    learner = pyonmttok.SentencePieceLearner(vocab_size=32000, character_coverage=0.98)
  File "/home/hanbing/miniconda3/envs/translate_server/lib/python3.7/tempfile.py", line 43, in <module>
    import shutil as _shutil
  File "/home/hanbing/miniconda3/envs/translate_server/lib/python3.7/shutil.py", line 22, in <module>
    import bz2
  File "/home/hanbing/miniconda3/envs/translate_server/lib/python3.7/bz2.py", line 17, in <module>
    from threading import RLock
  File "/home/hanbing/miniconda3/envs/translate_server/lib/python3.7/threading.py", line 8, in <module>
    from traceback import format_exc as _format_exc
  File "/home/hanbing/miniconda3/envs/translate_server/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/home/hanbing/miniconda3/envs/translate_server/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/home/hanbing/tmp/train_spm/tokenize.py", line 4, in <module>
    learner = pyonmttok.SentencePieceLearner(vocab_size=32000, character_coverage=0.98)
AttributeError: module 'tempfile' has no attribute 'mkstemp'
```

**Comment by guillaumekln** [comment]
You should rename your Python file `tokenize.py` to something else. `tokenize` is also a standard Python module.
